[redhat] Fix parsin of time with time zone indicator
The upstream feed must have changed recently, adding the Z at the end of the
time string. We had a wall of:

$ redhat2nvd -download -convert -since 240h > redhat-nvd.json
[...]
2020/01/28 11:23:23 convertutils.go:41: unable to parse time: parsing time "2020-01-22T00:00:00Z": extra text: Z
2020/01/28 11:23:23 main.go:162: error while converting vuln: unable to convert published date: parsing time "2020-01-22T00:00:00Z": extra text: Z

This error was preventing CVE entries from being converted and those entries
weren't present in the final NVD feed.